# Generated by Django 6.0.7 on 2026-07-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
