# Generated by Django 6.0.7 on 2026-07-30 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_human_takeover',
            field=models.BooleanField(default=False),
        ),
    ]
