import { formatDateTime } from './index'

/**
 * Download chat conversation as a clean .txt file
 */
export function exportChatAsTxt(sessionTitle, messages = []) {
  const title = sessionTitle || 'Chat Conversation'
  const dateStr = new Date().toLocaleDateString()
  let content = `==================================================\n`
  content += `SupportGenie AI — Chat Transcript\n`
  content += `Session: ${title}\n`
  content += `Exported: ${dateStr}\n`
  content += `==================================================\n\n`

  messages.forEach((msg, idx) => {
    const roleLabel = msg.role === 'user' ? 'Customer' : 'SupportGenie AI'
    const time = msg.created_at ? formatDateTime(msg.created_at) : ''
    content += `[${roleLabel}] ${time}\n`
    content += `${msg.content}\n`
    if (msg.sources && msg.sources.length > 0) {
      content += `Sources: ${msg.sources.map(s => s.source || s).join(', ')}\n`
    }
    content += `--------------------------------------------------\n\n`
  })

  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_transcript.txt`
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Export chat conversation as a styled PDF via browser print window
 */
export function exportChatAsPdf(sessionTitle, messages = []) {
  const title = sessionTitle || 'Chat Conversation'
  const dateStr = new Date().toLocaleDateString()

  const printWindow = window.open('', '_blank')
  if (!printWindow) return

  const html = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title} - SupportGenie AI Transcript</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 40px; color: #1e293b; max-width: 800px; margin: 0 auto; }
          .header { border-bottom: 2px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; }
          .title { font-size: 24px; font-weight: 800; color: #4f46e5; margin: 0 0 4px 0; }
          .meta { font-size: 13px; color: #64748b; margin: 0; }
          .msg { margin-bottom: 20px; padding: 16px; rounded-radius: 12px; border-radius: 12px; }
          .msg-user { background-color: #f1f5f9; border-left: 4px solid #64748b; }
          .msg-ai { background-color: #eef2ff; border-left: 4px solid #6366f1; }
          .sender { font-size: 12px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 6px; }
          .sender-user { color: #475569; }
          .sender-ai { color: #4f46e5; }
          .content { font-size: 14px; line-height: 1.6; white-space: pre-wrap; }
          .sources { font-size: 11px; color: #64748b; margin-top: 8px; font-style: italic; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 16px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 class="title">SupportGenie AI</h1>
          <p class="meta">Session: <strong>${title}</strong> &bull; Exported on ${dateStr}</p>
        </div>
        ${messages.map(m => `
          <div class="msg ${m.role === 'user' ? 'msg-user' : 'msg-ai'}">
            <div class="sender ${m.role === 'user' ? 'sender-user' : 'sender-ai'}">
              ${m.role === 'user' ? '👤 Customer' : '🤖 SupportGenie AI'}
            </div>
            <div class="content">${m.content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
            ${m.sources && m.sources.length ? `<div class="sources">Sources: ${m.sources.map(s => s.source || s).join(', ')}</div>` : ''}
          </div>
        `).join('')}
        <div class="footer">Generated by SupportGenie AI Customer Support Assistant</div>
        <script>
          window.onload = function() { window.print(); }
        </script>
      </body>
    </html>
  `

  printWindow.document.write(html)
  printWindow.document.close()
}
